hotzone_config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from addLocation.views import *
from viewCases.views import *
from login.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('logout/', logout_view),
    path('', auth_views.LoginView.as_view(template_name='login.html')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('create_caserecord_post/', CaseRecordAPI.as_view(),
         name='create_caserecord_post'),
    path('create_visitedlocation_post/', CreateVisitedLocationAPI.as_view(),
         name='create_visitedlocation_post'),
    path('create_caserecord/', CreateCaseRecordView.as_view(),
         name="create_caserecord"),
    path('post_caserecord/', CreateCaseRecordAPI.as_view(), name="post_caserecord"),
    path('create_virus/', CreateVirusView.as_view(), name='create_virus'),
    path('post_create_virus/', CreateVirusAPI.as_view(), name='post_create_virus'),
    path('index/', IndexView.as_view(), name='index'),
    path('create_visitedlocation/<int:caseID>',
         CreateVisitedLocationView.as_view(), name='create_visitedlocation'),
    path('locations/', LocationView.as_view(), name='locations-information'),
    path('search_location_post/', LocationWithMatchOnTopView.as_view(),
         name='search_location_post'),
    path('all_caserecord_post/<int:pk>/', ViewLocationRecordsView.as_view(),
         name="viewLocationRecords"),
    path('all_caserecord_post/', AllCaseRecord.as_view(),
         name="all_caserecord_post"),
    path('search_caserecord_post/', SearchCaseRecord.as_view(),
         name='search_caserecord_post/'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

addLocation/models.py
from django.db import models
from viewCases.models import CaseRecord
# Create your models here.


class Location(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=500, null=True)
    xcoord = models.FloatField()
    ycoord = models.FloatField()

    def __str__(self):
        return self.name


class VisitedLocation(models.Model):
    dateFrom = models.DateField()
    dateTo = models.DateField()
    category = models.CharField(max_length=20)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    caseRecord = models.ForeignKey(CaseRecord, on_delete=models.CASCADE)

    def __str__(self):
        return self.location.name + ", " + self.dateFrom.strftime("%Y-%m-%d") + " to " + self.dateTo.strftime("%Y-%m-%d")

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import logout
from django.shortcuts import redirect

def logout_view(request):
    logout(request)
    return(redirect('/login'))

templates/create_case_record.html
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/create_case_record.js' %}"></script>
<a href="{% url 'index' %}">Back to HotZone Index Page</a>
<h1>Create Case Record</h1>
<form id="createCaseForm" action="" method="post">
    <label for="name">Patient Name: </label><input type="text" id="name" name="name"><br>
    <label for="idNumber">Identity Document Number: </label><input type="text" id="idNumber" name="idNumber"><br>
    <label for="dateOfBirth">Date of Birth: </label><input type="date" id="dateOfBirth" name="dateOfBirth"><br>
    <label for="virus">Virus Name: </label>
    <input list="virus" name="virus" id="virus_input">
    <datalist id="virus">
        {% for virus in viruses %}
        <option value="{{virus.name}}"></option>        
        {% endfor %}
    </datalist><br>
    <label for="dateOfConfirm">Date Confirmed: </label><input type="date" id="dateOfConfirm" name="dateOfConfirm"><br>

    <label for="localOrImported">Local or Imported Case: </label><br>
    <input type="radio" id="lol1" name="localOrImported" value="Local"><label for="lol1">Local</label><br>
    <input type="radio" id="lol2" name="localOrImported" value="Imported"><label for="lol2">Imported</label><br><br>

    <input type="button" id="createButton" value="Create Case">
    <!-- <input type="button" value="Generate Json" onclick="generateJson()"> -->


</form>
<p id="createStatus"></p>

templates/create_virus.html
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/create_virus.js' %}"></script>
<a href="{% url 'index' %}">Back to HotZone Index Page</a>
<h1>Create New Virus Record</h1>
<form id="createVirusForm" action="">
    <label for="name">Virus Name: </label><input type="text" id="name" name="name"><br>
    <label for="commonName">Common Name: </label><input type="text" id="commonName" name="commonName"><br>
    <label for="maxInfectiousPeriod">Max Infectious Period: </label><input type="number" id="maxInfectiousPeriod" name="maxInfectiousPeriod"><br>
    <input type="button" id="createButton" value="Create Virus Record">
    <!-- <input type="button" value="Reset" onclick="resetForm()"> -->
</form>
<p id="createStatus"></p>

templates/create_visited_location.html
{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="{% static 'js/retrieve_location.js' %}"></script>

<a href="{% url 'index' %}">Back to HotZone Index Page</a>

<div>You are now adding a visited location record for {{case.patient.name}} (id:<span id="caseID">{{case.pk}}.</span>)</div><br>

<form id="addLocationForm" action="" method="post">
    <div><label for="dateFrom">Date from: </label><input type="date" id="dateFrom" name="dateFrom"></div>
    <div><label for="dateTo">Date to: </label><input type="date" id="dateTo" name="dateTo"></div><br>
    <label for="categoryRadio">Category:</label>
    <div id="categoryRadio">
        <input type="radio" id="category1" name="category" value="Residence"><label for="category1">Residence</label><br>
        <input type="radio" id="category2" name="category" value="Visit"><label for="category2">Visit</label><br>
        <input type="radio" id="category3" name="category" value="Workplace"><label for="category3">Workplace</label><br><br>
        <label for="q">Location (Click "Retrieve" after entering location)</label><br>
        <span><input type="text" id="location" name="q" placeholder="Enter location in here"></span>
        <span><input type="button" onclick="retrieve()" value="Retrieve"></span>
        <p id="retrieveStatus"></p>
    </div>
    <label for="locationRadio">Retrieved location result(s) (Select below)</label>
    <table id="locationTable" class="display" style="width: 100% ; height: 500px">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>X-coordinate</th>
                <th>Y-coordinate</th>
            </tr>
        </thead>
    </table>
    <span>
        <input id="confirmButton" type="button" value="Confirm" disabled=true>
    </span>
    <div id="confirmStatus"></div>

</form>

<!-- <button onclick="checkSelectedLocation()">check Selected Location</button>
<button onclick="simulatePOSTfrom()">simulate POST from</button>
<button onclick="generateJson()">generateJson</button> -->

<!--<h1>Location Record</h1>-->

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>HotZone</title>
  </head>
  <body>
    <h1>HotZone</h1>
    <button onclick="location.href='../logout'">Logout</button>

    <ul>
      <li><a href="{% url 'all_caserecord_post' %}">View All Cases</a></li>
      <li>
        <a href="{% url 'create_caserecord' %}">Create New Case Record</a>
      </li>
      <li><a href="{% url 'create_virus' %}">Create New Virus Record</a></li>
      <li>
        <a>Add Visited Location Record for Case ID:</a>
        <input list="cases" id="case_input" />
        <datalist id="cases">
          {% for case in cases %}
          <option value="{{case.pk}}"></option>
          {% endfor %}
        </datalist>
        <button
          type="button"
          onclick="location.href='../create_visitedlocation/' + document.getElementById('case_input').value"
        >
          Go
        </button>
      </li>
      <li>
        <a href="{% url 'locations-information' %}">View All Saved Locations</a>
      </li>
    </ul>
  </body>
</html>

templates/location_list.html
<h1>Saved Locations</h1>
<a href="{% url 'index' %}">Back to HotZone Index Page</a>
<ul>
{% for location in location_list %}
    <li>{{location.name}}
        <ul>{{location.address}}
            <li>{{location.xcoord}}</li>
            <li>{{location.ycoord}}</li>

        </ul>
    </li>
    {% empty %}
    <li>No Locations yet.</li>
    {% endfor %}
</ul>

templates/login.html
<h1> Welcome to HotZone! </h1>
<p> Test = username: user123, password: comp3297</p>
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Login">
<input type="hidden" name="next" value="/index">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'index' %}">Reset password (not yet implemented)</a></p>

templates/view_all_cases.html
{% load static %}
<!DOCTYPE html>
<html>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <head>
    <meta charset="utf-8">
    <title>Case Records</title>
  </head>
  <body>
    <h1>Case Records</h1>
    <a href="{% url 'index' %}">Back to HotZone Index Page</a>
    <p>Select a case to view location records and add visited locations.</p>
    {% if case_records %}
        <table style="width: 60%">
          <tr>
            <th> Patient </th>
            <th> Date of Confirmed </th>
            <th> Virus </th>
            <th> Local/Imported</th>
            <th> Action </th>
          </tr>
        {% for case in case_records %}
          <tr>
            <td>{{ case.patient }}</td>
            <td>{{ case.dateOfConfirm }}</td>
            <td>{{ case.virus }}</td>
            <td>{{ case.localOrImported }} </td>
            <td><a href="{% url 'viewLocationRecords' case.id %}"> View Location Records </a></td>
          </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No case records are available.</p>
    {% endif %}
  </body>
</html>

templates/view_location_records_for_a_case.html
{% load static %}
<!DOCTYPE html>
<html>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <head>
    <meta charset="utf-8">
    <title>Location Records</title>
  </head>
  <body>
    {% csrf_token %}
    <h1>{{ caserecord.patient.name }}'s Location History</h1>
    <a href="{% url 'all_caserecord_post' %}" style="display:block;">Back to Case Records</a>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <table style="width: 60%">
      <tr> 
        <th> Location </th>
        <th> Category </th>
        <th> Date From</th>
        <th> Date To</th>
      </tr>
    {% for location in caserecord.visitedlocation_set.all %}
      <tr>
        <td> {{ location.location }} </td>
        <td> {{ location.category }}</td>
        <td> {{ location.dateFrom }}</td>
        <td> {{ location.dateTo }} </td>
      </tr>
    {% endfor %}
    </table>
    <a href="{% url 'create_visitedlocation' caserecord.id %}">Add Visited Location for {{ caserecord.patient.name}}</a>
    </ul>
  </body>
</html>